/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class learn_jni_Sample01 */

#ifndef _Included_learn_jni_Sample01
#define _Included_learn_jni_Sample01
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     learn_jni_Sample01
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_learn_jni_Sample01_square
  (JNIEnv *, jobject, jint);

/*
 * Class:     learn_jni_Sample01
 * Method:    aBool
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_learn_jni_Sample01_aBool
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     learn_jni_Sample01
 * Method:    text
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_learn_jni_Sample01_text
  (JNIEnv *, jobject, jstring);

/*
 * Class:     learn_jni_Sample01
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_learn_jni_Sample01_sum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
